include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_void_async
    - unawaited_futures
    - unnecessary_await_in_return

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'lib/config/*.dart'
    - 'lib/locator.config.dart'
    - 'lib/locale_keys.g.dart'
