name: jarvis_ai
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^3.0.2

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.3.3

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
  injectable_generator: ^2.6.1

  # retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit_generator: ^8.1.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.5.4

  # Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
  copy_with_extension_gen: ^5.0.0

  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen_runner: ^5.1.0+1

  # Checks for missing, under-promoted, over-promoted, and unused dependencies.
  dependency_validator: ^3.2.2




flutter_gen:
  output: lib/gen/
  line_length: 150

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/langs/

